= Rationneur

== Introduction

=== Domaines métiers / Noms de package.

Bonjour,

En mettant à jour le D.A.T, ceci m'a semblé important / à partager :
Correspondance du découpage en module / connecteurs vers objets de données.
( Les lignes en commentaires ne sont pas implémentées)



Les différents composants de la solution adoptent un découpage en domaines métiers, liés aux connecteurs, qui est le suivant :

/security
/tenants
/licenses
/farms
/library
/settings
/rations
/engine
/parser

détails :

    // * accounts : connecteur permettant de synchroniser des comptes auprès d'un connecteur d'authentification externe (§openauth, ldap).
    * security : les utilisateurs et les profils au sein du rationneur
      1. User : utilisateur
      2. Profile : Profil (super admin, éleveur, utiilisateur, etc...) contients des droits.
      3. Feature : Droit d'utilisation. (instance de FeatureCode sur un profil)
    // ` UserSettings : préférences d'un utilisateur (entêtes de colonnes etc)
    * tenants : les entités
      1. Tenant : occupant/locataire de l'application
    * licenses : les licenses d'utilisation.
      1. LicenseFile : Fichier de license, contitne une liste de droits (Feature) et de catégorie animales (AnimalCategory)
      2. License : license installée dans l'application, répartie sur des entités.
    * farms : élevage, regroupe les élevage et les informations des animaux
      1. Farm : élevage
      2. AnimalHerd : animal d'un troupeau
    //  3, Herd : (troupeau/lot) subdivision des animaux.
    * library : les aliments, les mélanges et les catalogue d'aliments.
      1. Catalog : catalogues d'aliment.
      2. Food : aliment (lié, copié ou fantôme)
      3. Mixture : un mélange est un aliment contenant des ingrédients.
      4, Ingredient: composant d'un mélange (aliment + pourcentage de répartition).
      3. Level : Niveau d'aliment (Sous catégories, de 1 à 9, permettent de filtrer les aliments)
      4. LevelConstraint : contraintes extraites du catalogue inra
      4. SubCategories : niveaux // et liaison avec les traductions.
      5. ErrorLog : erreurs d'import du catalogue inra.
    * settings : le paramétrage de l'application par entité et par catégorie animale
      1. Characteristic : Caractéristiques
        a. FoodCharacteristic : d'aliments
          1. par type d'aliment : FoodCharSettings
        b. RationCharacteristic : de rations
          2. par type de ration : RationCharSettings
      2. RubricConfig : Rubriques de contexte
      3. InraCatalog : Catalogue inra : objet de transfert utilisé pour l'import
        a. LevelConstraints : Contraintes de niveaux
        b. SubCategories : Traduction des libellés
        c. Aliments d'origine
       4.Strategy : Stratégies : influence les entrée du moteur selon le poids ou la semaine de lactation de l'animal
         a. StrategyLine : Ligne de stratégie _ valeur par colonne.
         b. StrategyColumnKey: Entête de colonne de stratégie.
       5. ScreenConfig : Configurations des caractéristiques affiches en fonction des zones d'écran
       6, RegionalData : Données régionales (module paturage)
    * rations  : les rations, les aliments de rations, et le stockage des résultats du moteur de calcul.
      1. Ration :
        a. RationDetail : encapsule les différents résultats d'appel au moteur ou les différents type de ration (à l'auge ou moyenne)
        b. RationFood : un aliment de ration et ses valeurs, créé depuis les aliments.
        c. RationCharValue : résultat d'un calcul.
        d. Context : le contexte de la ration, en fonction de la catégorie animale.
      2, Context :
        a. .rubrics : rubrique de contexte.
        b. RubricKey / RubricValueType : un contexte est une liste de clé / valeurs basé sur les settings.RubricConfig
    * engine : l'appel du moteur de calcul INRA, moteur d'analyse des formules de calcul.
      1. EngineCallContext : Les paramètres d'entrée de l'application à un instant T.
      2. adapters : adaptateurs entre les données du rationneur et les caractéristiques du moteur INRA.
      3. formula : parseur de formules / expressions mathématiques.

Coté back uniquement
    * api : objets de transfert et interfaces de connecteur/services.
    * utils/config : packages de configuration
    * parser : Lecteurs d'annexes, extrait le paramétrage initial du domaine 'settings' depuis les annexes.
      1. foodChar : Caractéristique d'aliments.
      2. rationChar : Caractéristique de rations.
      3. inraCatalog : Catalogue INRA (traductions, niveaux etc...)
      4. rubricConfigs : Rubriques de contexte

Coté front uniquement :

    * global : services partagés
      1. Message : alertes flash de succès erreur: réussite en haut à droite.
      2. Modal
    * main :
      1. header/footer
      2. layout
    * components : librairie internes de conmposants léger / transverse
    * services : couche de services / modèle pour le front.


En continuant comme ça dans le reste à faire :

* pcg : module pcg
  // todo
  PcgRubricConfig : sous classe de RubricConfig, paramétrage de rubrique lié uniquement à la Vache Laitière
  Pcg
* pasture : module pâturage
  1. PastureInfos : calqué avec les enums en entrée du moteur.
* i18n : connecteur technique, gère(rait) les traductions des différents libellés
  1. Translation (traduction ((langue + clé) = libellé)
  2. TranslationEntry (clé + liaison avec les traductions par langage + type d'objet/ de champ à traduire)


== UI

 core
